### ISSUE TITLE
bug: Crash on Fabric on version 1.3.0

### ISSUE THREAD

**Issue by CaseyPurser** [adibarra/enchant-tweaker#1]
### What happened?

When running Debugify and Enchant Tweaker at the same time a crash occurs.

Log: https://mclo.gs/H7gTgEa 

### What should have happened?

Previously these mods worked fine together in Enchant Tweaker version 1.2.1 there was no crashing and no issues.

### How to reproduce?

1. Install Debugify version 2.2
2. Install Enchant Tweaker 1.3.0
3. Run Fabric Loader on version 0.14.19

### What is the jar file name?

enchanttweaker-1.3.0+mc1.19.4

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by CaseyPurser** [comment]
Update: Tested running the mod without Debugify and it still crashes. Running the mod on a fresh install of Fabric leads to a similar crash. 

https://mclo.gs/T5RFOSf

**Comment by adibarra** [comment]
On first look this seems to be a bug exclusive to using Quilt that appeared after a dependency upgrade. I'll look into getting it to be compatible.

**Comment by adibarra** [comment]
The issue has been fixed and will be available in the next update (v1.3.1). Thanks for the bug report!

**Comment by CaseyPurser** [comment]
Thank you for the working to fix this so quickly. Unfortunately, I'm still running into crashes when trying to run the mod on Fabric.

Log: https://mclo.gs/f7I3ACP

I ran into the same problem when running Quilt. Both of these are on fresh instances using Prism Launcher.

Log: https://mclo.gs/mS6c1bE

**Comment by adibarra** [comment]
Alright, should actually be fixed now. Strange that I didn't catch that one earlier. It'll be included in the next update (v1.4.0).

**Comment by CaseyPurser** [comment]
Just tested the new update and everything seems to be fixed now. Thank you!
