### ISSUE TITLE
feat: Add the option to merge redundant enchantments

### ISSUE THREAD

**Issue by Malachi-lewis** [adibarra/enchant-tweaker#15]
### What does it do?

This would merge fire aspect/flame, knockback/punch, looting/fortune/luck of the sea, and efficiency/lure into single enchantments that are compatible with all items. So fire aspect bows, looting pickaxes, etc.

### Why add it?

This would make exploration more viable as a way of getting enchanted gear, as you would have a lower chance of getting unwanted books with useless combinations.

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
This is a pretty great idea but I think it's a little out of scope for this project. I'd highly recommend posting it in the #requests channel in the [fabric discord server](https://discord.gg/v6v4pMv). Thanks for the suggestion though.
