### ISSUE TITLE
feat: 1.20.4 Update

### ISSUE THREAD

**Issue by ghost** [adibarra/enchant-tweaker#17]
### What does it do?

I can enjoy your mod again !

### Why add it?

This is a major official update why the new bulb and auto-crafter block

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Support for MC 1.20.3 and 1.20.4 is now available in version 1.4.6 of Enchant Tweaker.
Thanks for the reminder to update it, haven't been keeping up lately.
