### ISSUE TITLE
1.20.2 Update

### ISSUE THREAD

**Issue by ghost** [adibarra/enchant-tweaker#18]
### What does it do?

update

### Why add it?

its a cool update

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, the mod does actually have a version that is compatible with 1.20.2. Looks like I forgot to tag them as such on Modrinth, I'll update it ASAP. Thanks for the report!

**Comment by ghost** [comment]
thank you !
