### ISSUE TITLE
bug: Trident Weapon Enchantments not Working v1.2.1

### ISSUE THREAD

**Issue by CaseyPurser** [adibarra/enchant-tweaker#2]
### What happened?

When using the previous version Tridents cannot have Sharpness, Smite, and Bane of Arthropods added using an anvil and book. Fire Aspect, Looting, and Knockback did not have any issues being added to a trident. 

### What should have happened?

In survival players should be able to add all weapon enchaments to a Trident using an anvil when the Trident Weapons config is set to true.

### What is the jar file name?

enchanttweaker-1.2.1+mc1.19.4

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
That's what I get for testing in creative... Next update (v1.3.1) should allow the damage enchantment to be added as well. Thanks for the bug report!
