### ISSUE TITLE
feat: Clarified Max Enchant Modification

### ISSUE THREAD

**Issue by fluffyxox** [adibarra/enchant-tweaker#22]
### What does it do?

Please clarify in the config how exactly the scaling applies. A short example would help as well.

### Why add it?

I am uncertain if this element of the mod allows you to actually exceed caps placed on things like Protection. Does anything beyond a full set of Protection V actually change incoming damage, and is there a cap?
Does adjusting the scaling simply mean raising the amount of steps between the minimum and the cap? (Protection 100 still being equal to 25 EPF, just with 99 decimal values between.)

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Vanilla enchantments have some formulas that scale how effective an enchantment is based on it's level. The mod just removes vanilla's max level caps. It's not that it increases the number of steps between the min and cap but that it actually allows the enchantments to become more powerful.

That said, as you mentioned, EPF is still a thing. The mod does not currently modify it so the effectiveness of Protection is currently capped to 25 EPF. Same deal with the other enchantments, if they have any built-in systems to cap them, like EPF, then it will respect those systems.

Some enchantments do have a special tweak that fixes these restrictions and does allow it to scale unrestricted. Unfortunately, Protection is not currently one of these. I'll add some clarification to the config. Thanks for the suggestion!
