### ISSUE TITLE
I cant configure mod!

### ISSUE THREAD

**Issue by vlad8599** [adibarra/enchant-tweaker#23]
### What happened?

No options in Mod Menu to configure various things. Tell me how to config mod, please.

### What should have happened?

I expected some menu in Mod Menu to configure various things.

### How to reproduce?

Find mod in Mod Menu, you can find mod, but you wont see button to open mod settings.

### What is the jar file name?

enchanttweaker-1.4.7+mc1.20.3-1.20.4.jar

### What Minecraft version?

Fabric 1.20.4

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, the mod does not currently have integration with ModMenu.

However you can modify the settings via its config file. The config file can be found in most installations at `.minecraft\config\enchant-tweaker.properties`. It should be in the same directory as the `mods` menu where you installed your mods.

If you are using a launcher such as Prism Launcher you can usually find a button in your mods section labeled `View Configs` which should take you to the right place. Hope this helps.

Feel free to reopen the issue if you run into any problems.
