### ISSUE TITLE
bug: Is "\config\config" the intended path for ET to be saving it's configuration?

### ISSUE THREAD

**Issue by evilryan** [adibarra/enchant-tweaker#26]
### What happened?

I am finding it in \config\config on my Fabric server. This is not a major issue, organizationally tickles my brain.

### What should have happened?

Most other mods place their config in \config\\<mod_name>\, I would imagine for ET it would be in \config\EnchantTweaker.

### How to reproduce?

Install Fabric Server (MC v1.20.4)
Install  vEnchant Tweaker 1.4.8+mc1.20.3-1.20.4 into the \mods folder.
Start the server for the first time. View/modify Enchant Tweaks settings as desired, look in \config folder and see enchant-tweaker.properties is in there.

### What is the jar file name?

enchanttweaker-1.4.8+mc1.20.3-1.20.4

### What Minecraft version?

Fabric 1.20.4

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
You are correct, this is not intended. I'll start looking into it.

**Comment by adibarra** [comment]
Actually, this seems to be the cause of issue #25 so I'll combine the two.

Thanks for the report! Fix will be out soon.
