### ISSUE TITLE
feat: "More Infinity" enchantment tweak

### ISSUE THREAD

**Issue by James103** [adibarra/enchant-tweaker#3]
### What does it do?

When the tweak is enabled, firing an arrow from a bow enchanted with Infinity has a _chance_ to not consume an arrow (based on enchantment level), instead of always preserving the arrow.

For example, each level of Infinity on a bow has a 10% chance to not consume an arrow when that bow is fired, up to 100% at Infinity X.

Arrows fired from such a bow can be picked up if and only if the shot consumed an arrow from the shooter's inventory.

### Why add it?

Some players may want an enchantment that is like Infinity but weaker than it, giving them a reason to carry and make several arrows (instead of just 1) while allowing the player to get more shots out of each arrow.

### Anything else?

The above idea is a reference to [a custom enchantment](https://hypixel-skyblock.fandom.com/wiki/Enchantments#Infinite_Quiver), whose name can be reproduced in a vanilla with the following lang file:
```json
{
  "enchantment.minecraft.infinity": "Infinite Quiver"
}
```

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Interesting idea! The only issue I can think of is that it would probably not work with `BowInfinityFix` enabled. That's an easy fix though since I could just make `MoreInfinity` override it. I'll look into implementing this. Thanks for the feature request.

**Comment by adibarra** [comment]
Just finished it, it'll be included in the next update (v1.4.0).
