### ISSUE TITLE
Mod does not work :(

### ISSUE THREAD

**Issue by Chief0609** [adibarra/enchant-tweaker#30]
### What happened?

This has happened multiple times, every time I go to use this mod and configure the setting how I would want and load the game no feature works, the max level tweak does not apply, anvil cost is not affected, and new/different enchantment properties are not applied (mending levels, channeling levels, etc.). I am unsure of what to do, if there are any mod dependencies or incompatibilities that don't crash the game. I am at a loss of what to do

### What should have happened?

I expected the mod to load and act as others have acted in the issues tab but it appears I'm the only one

### How to reproduce?

1. download the mod in question and the other mods
2. launch mc
3. boom: mod doesn't work

### What is the jar file name?

1.4.9+mc1.20-1.20.1

### What Minecraft version?

Fabric 1.20.1 | Loader: 15.7

### Any relevant logs?

heres my list of mods to help replicate this: (includes imbedded mods I think)

	- accurateblockplacement 1.2.1
	- amecs 1.3.10+mc.1.20.1
	   \-- amecsapi 1.4.0+mc1.20-pre1
	- animatica 0.6+1.20
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- armorstatues 8.0.5
	   \-- puzzlesapi 8.1.4
	        |-- cardinal-components-base 5.2.2
	        |-- cardinal-components-entity 5.2.2
	        \-- puzzlesaccessapi 8.0.7
	- armortrimitemfix 1.0.2
	- autototem 1.20.1-1.0.3
	- bedrockminer 1.20.1-1.2.1
	- better-trim-tooltips 1.0.1
	- betterf3 7.0.2
	- betterhurtcam 1.5.5
	   \-- betterhurtcam-mc120 1.5.5
	- blur 3.1.0
	   |-- midnightlib 1.4.1
	   \-- satin 1.13.0
	- boatbreakfix 1.0.11
	- boatiview 0.0.5
	- breakfree 1.2.0
	- c2me 0.2.0+alpha.11.5
	   |-- c2me-base 0.2.0+alpha.11.5
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.5
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.5
	   |-- c2me-notickvd 0.2.0+alpha.11.5
	   |-- c2me-opts-allocs 0.2.0+alpha.11.5
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.5
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.5
	   |-- c2me-opts-math 0.2.0+alpha.11.5
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.5
	   |-- c2me-server-utils 0.2.0+alpha.11.5
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.5
	   |-- c2me-threading-lighting 0.2.0+alpha.11.5
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.5
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- carpet 1.4.112+v230608
	- chatanimation 1.0.5
	- chunksfadein 1.0.5-1.20.1
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- clickcrystals 1.20.1-1.2.2
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- colormeoutlines 1.1.2
	- continuity 3.0.0-beta.4+1.20.1
	- cullleaves 3.2.0
	   \-- midnightlib 1.4.1
	- dashloader 5.0.0-beta.2+1.20.0
	   |-- com_github_luben_zstd-jni 1.5.2-2
	   |-- dev_notalpha_taski 2.1.0
	   \-- dev_quantumfusion_hyphen 0.4.0-rc.3
	- draggable_lists 1.0.1
	- dynamic_fps 3.4.2
	- eatinganimationid 1.20+1.9.5
	- enchantedtooltips 1.3.7-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- enchanttweaker 1.4.9+mc1.20-1.20.1
	- enhanced_attack_indicator 1.0.4+1.20
	- entity-view-distance 1.1.2+1.20
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   \-- spruceui 5.0.0+1.20
	- entityculling 1.6.2-mc1.20.1
	- essential-container 1.0.0
	   \-- essential-loader 1.2.1
	- exordium 1.2.1-mc1.20.1
	- explosiveenhancement 1.2.2-1.20.x
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.18+kotlin.1.9.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.2
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.2
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- faster_entity_animations 1.6
	- ferritecore 6.0.1
	- foodeffecttooltips 1.1.1-1.20.0
	- forgeconfigapiport 8.0.0
	- freecam 1.2.1+1.20
	- gammautils 1.7.16
	- indium 1.0.30+mc1.20.4
	- invmove 0.8.4
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- jei 15.3.0.4
	- jeresources 1.4.0.247
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- librarian-trade-finder 2.0.1
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.3
	- minecraft 1.20.1
	- mobility 1.2.1
	- modmenu 7.2.2
	- moreculling 1.20.4-0.22.1
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- mousetweaks 2.25
	- nameplate 1.1.4
	- nmc 2.1
	- notenoughanimations 1.7.1
	- overlaytweaks 1.7.3
	- perspectivemod 0.0.5_01
	- puzzleslib 8.1.17
	   \-- puzzlesaccessapi 8.0.7
	- quick_hotkeys 1.0.2
	- reacharound 1.1.2
	- reeses-sodium-options 1.7.2+mc1.20.1-build.101
	- shulkerboxtooltip 4.0.4+1.20.1
	- smallviewmodel 1.0
	- sodium 0.5.8+mc1.20.1
	- sodium-extra 0.5.4+mc1.20.1-build.115
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- spark 1.10.53
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- strongholdfinder 0.1.0
	- threadtweak 1.20.2-0.1.1
	- tia 1.20-1.1
	- tiefix 1.14.0
	- tooltipfix 1.1.1-1.20
	- ukulib 0.7.0+1.20
	   \-- gs_mclo_java_mclogs-java 2.1.1
	- visuality 0.7.1+1.20
	- voicechat 1.20.1-2.5.7
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6

### Anything else?

Im going to attempt to to find out if its an incompatibility 

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by Chief0609** [comment]
I just tried it with no other mod enabled but fabric 0.92.0 and the newest version of enchant tweaker and still did nothing

**Comment by adibarra** [comment]
Hello!
I was able to replicate this and it seems to be an issue with that specific build of the mod (v1.4.9 for 1.20.1). I'll start looking into it. Thanks for the report.

**Comment by adibarra** [comment]
I've released v1.4.9.1 for MC 1.20.1 which should have fixed the issue. Please reopen the issue if you run into any further problems!

**Comment by Chief0609** [comment]
> Hello! I was able to replicate this and it seems to be an issue with that specific build of the mod (v1.4.9 for 1.20.1). I'll start looking into it. Thanks for the report.

no problem, thanks for responding so quickly

**Comment by octoshrimpy** [comment]
Any chance this could be pushed for 1.20.2? 

![image](https://github.com/adibarra/enchant-tweaker/assets/7097172/16b35b17-32e6-4176-b99b-80a3d4a91612)
I have unbreaking set to 10, yet it still glows yellow on 3. 
I've uploaded my config file
[enchant-tweaker.properties.txt](https://github.com/adibarra/enchant-tweaker/files/14685442/enchant-tweaker.properties.txt)

**Comment by adibarra** [comment]
@octoshrimpy Hello, please create and fill out a new issue. Your problem seems to be completely unrelated to the one described here.
