### ISSUE TITLE
bug: 1.20.2 -  Max enchant level does not work

### ISSUE THREAD

**Issue by octoshrimpy** [adibarra/enchant-tweaker#31]
### What happened?

loaded mod, modified config in-game to recommended enchant levels, reloaded minecraft completely. 
max enchants do show as yellow, but the max enchant level was not modified.

### What should have happened?

max enchant levels should be increased (to 10, for example). 
Instead, it stays at vanilla max

### How to reproduce?

install mod, load up MC, change max levels, reload game

### What is the jar file name?

v1.4.9+mc1.20.2

### What Minecraft version?

Fabric 1.20.2

### Anything else?

also tested with v1.4.9.1+mc1.20-1.20.1, no luck. 

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello! Just to be clear are you running any other mods in addition to Enchant Tweaker?

**Comment by octoshrimpy** [comment]
I do have a few mods added as well. I'm loading up a new instance with just enchant tweaker for testing.

**Comment by octoshrimpy** [comment]
In a new instance with just ET installed, 
- set a few enchants to max level 10, and enabled god armor.  
- restarted minecraft completely.

- cannot go higher than efficiency 5 in an anvil
- cannot go higher than unbreaking 3 in an anvil

mod is enabled, and both are set to max 10.
![image](https://github.com/adibarra/enchant-tweaker/assets/7097172/30ef3204-2b8c-42fb-9cd9-54b610c18123)

----

- enabled shiny names
- restarted MC completely
- /et reload            # just in case

as you can see from the video, the names are yellow as vanilla-maxed, not the custom value of 10 defined in config.
also, the names glitch and come right back sometimes, unsure why that is; also visible in video.

https://github.com/adibarra/enchant-tweaker/assets/7097172/8317a87b-b249-4e11-8226-2f18502fac6b

here is config, file renamed to `enchant-tweaker.properties.txt` to allow github upload: 
[enchant-tweaker.properties.txt](https://github.com/adibarra/enchant-tweaker/files/14894042/enchant-tweaker.properties.txt)

---

also there is nothing in the logs other than messages about changing config values or reloading.

**Comment by adibarra** [comment]
Ok, I found whats going on in this case. Whenever you want to enable the ability to change the max enchantment levels. There is an additional setting that needs to be set. Try setting `capmod_enabled` to true.

![image](https://github.com/adibarra/enchant-tweaker/assets/93070681/04dae00c-945f-410c-9059-33201c126f9c)

**Comment by 3ri4nG0ld** [comment]
Just now I was testing and I have the same problem (mc1.20.4), I have configured the mod to have level 10 limit on many enchantments, but they don't apply.

I have "capmod_enabled" and "mod_enabled" set to true.

**Comment by adibarra** [comment]
Hello @3ri4nG0ld, please create a new issue describing the problem you are encountering when you get the chance.

**Comment by octoshrimpy** [comment]
@adibarra after enabling that setting and reloading, it appeared it did not work. I disabled shiny names and reloaded, and that worked. Thank you! issue solved: 

enable `capmod_enabled`
