### ISSUE TITLE
bug: “Too Expensive!” text still shows even with both client and server install

### ISSUE THREAD

**Issue by Nyarumi** [adibarra/enchant-tweaker#32]
### What happened?

Mod is installed on both server and client yet “Too Expensive!” text still appears even with the proper settings enabled.

### What should have happened?

“Too Expensive!” text should be hidden. True cost of anvil combination should be shown (unsure if this feature is supported).

### How to reproduce?

1. Install mod on client and server
2. Enable the “not too expensive” setting
3. Attempt to combine two expensive items in an anvil
4. See the “Too Expensive!” text still appear

### What is the jar file name?

enchanttweaker-1.4.9+mc1.20.3-1.20.4.jar

### What Minecraft version?

Fabric 1.20.4

### Any relevant logs?

Enchant Tweaker settings: https://mclo.gs/KlH1SzT
Mod list: https://mclo.gs/We9PSs4

### Anything else?

The result of the combination can be seen in the anvil which I think means not too expensive is working, it’s just the “Too Expensive!” text is still there. Have not been able to actually confirm it works though as true cost is not visible and have only tried at level 40.

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello! This sounds like a problem caused by the mod config not being set up client side.

To be clear, you need to make sure that "Not To Expensive" is enabled in both the server and client config files. It does not automatically sync the server config to the client (yet).

Please let me know if this fixes the problem you are encountering. Thanks.

**Comment by Nyarumi** [comment]
You are completely right, that was the issue. My apologies for wasting your time on this. Maybe an additional comment noting that it needs to be set on both the server and the client might help other people down the line. Thank you!
