### ISSUE TITLE
bug: the config file doesn't work

### ISSUE THREAD

**Issue by sylv3str4** [adibarra/enchant-tweaker#39]
### What happened?

So I installed the mod yesterday and used the config to change things but when I joined my world, it didn't work! didn't

### What should have happened?

All enchants tweak I have enabled should work, the enchant cap should changed

### How to reproduce?

1. Download the mod
2. Change the config file
3. Join the game
4. Create a creative world to test out all the mods
5. It didn't work
6. Check the config file again
7. Reload world
8. It still didn't work

### What is the jar file name?

enchanttweaker-1.4.9+mc1.20.3-1.20.4.jar

### What Minecraft version?

Fabric 1.20.4

### Any relevant logs?

Nothing

### Anything else?

Nothing

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, it seems you might have missed setting `capmod_enabled=true` at line 243 in the config file. Could you please check and update this setting? Let me know if this resolves your issue or if you continue to experience problems.

Thanks!

**Comment by sylv3str4** [comment]
Thanks!
