### ISSUE TITLE
feat: Mod not working

### ISSUE THREAD

**Issue by DeadlyWolf3** [adibarra/enchant-tweaker#40]
### What does it do?

Help pls ! xD

### Why add it?

I really want to play with this mod but it doesn't seem to work when im in singleplayer
hopefully anyone can help me

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, please open a new issue using the bug report template and be sure to fill it all in. All of that information is important for me to be able to help you.

**Comment by adibarra** [comment]
#41
