### ISSUE TITLE
bug: Mod not working

### ISSUE THREAD

**Issue by DeadlyWolf3** [adibarra/enchant-tweaker#41]
### What happened?

mod not working

### What should have happened?

that i played in singleplayer and could've get my enchants a bit higher then the standard lvls

### How to reproduce?

dont know what to put down here srry

### What is the jar file name?

enchanttweaker-1.4.9+mc1.20.3-1.20.4 (1).jar

### What Minecraft version?

fabric 1.20.4

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Hello, thanks for remaking your issue. Can you attach your config file for the mod when you get the chance.

**Comment by DeadlyWolf3** [comment]
maybe stupid to ask but where do i see the config file and how can i attach it to it

**Comment by DeadlyWolf3** [comment]
i cant put the file in it

**Comment by adibarra** [comment]
Can you try copying and pasting just the contents of the file into a comment.

**Comment by DeadlyWolf3** [comment]
do u mean the inside of the config? with the things that i can enable / turn to true or false or do u mean something else

**Comment by adibarra** [comment]
Yes, that's the one.

**Comment by DeadlyWolf3** [comment]
This is after i edited it 
####################################################################################################
####  Enchant Tweaker Config
####################################################################################################

    ################################################################################
    ###   Master Switch:
    ###    Enable/Disable the entire mod.
    ###
           mod_enabled=Enable
    ###
    ################################################################################

    ################################################################################
    ###  Anvil Tweaks:
    ###    Some small anvil related tweaks. Lightly alters the anvil's mechanics.
    ###
    ###    ########################################
    ###    ##  Cheap Names:
    ###    ##    Normally renaming an item will cost a similar amount of levels as adding an enchantment onto an item.
    ###    ##    Enabling this will force the cost for renaming items to always be one level.
    ###    ##    For those who don't enjoy spending nineteen levels to rename a pickaxe... again.
    ###    ##
                 cheap_names=true
    ###    ##
    ###    ########################################
    ###    ##  Not Too Expensive:
    ###    ##    Normally once an item's enchant/repair cost reaches 40 levels you can no longer enchant or repair it.
    ###    ##    Enabling this tweak alters the "Too Expensive!" mechanic in the anvil changing the level it activates at to one of your choosing.
    ###    ##    Client-side install will hide the "Too Expensive!" message. Otherwise, it will still appear but will not prevent the action.
    ###    ##
                 not_too_expensive=true
                 nte_max_cost=2147483647
    ###    ##
    ###    ########################################
    ###    ##  Prior Work is Cheaper:
    ###    ##    Normally when enchanting/repairing an item, each operation will double the cost of the next action.
    ###    ##    Enabling this tweak will let you customize the penalty.
    ###    ##
                 prior_work_cheaper=true
                 pw_cost_multiplier=1.33
    ###    ##
    ###    ########################################
    ###    ##  Prior Work is Free:
    ###    ##    Normally when enchanting/repairing an item, each operation will double the cost of the next action.
    ###    ##    Enabling this tweak completely disables the prior work penalty for items enchanted/repaired at an anvil.
    ###    ##    This means that the enchant/repair cost for an item will always stay at the minimum value for that given procedure.
    ###    ##
                 prior_work_free=true
    ###    ##
    ###    ########################################
    ###    ##  Sturdy Anvils:
    ###    ##    Normally an anvil has a 12% (0.12) chance to take damage when used.
    ###    ##    Enabling this tweak will let you customize the damage chance.
    ###    ##
                 sturdy_anvils=true
                 anvil_damage_chance=0.06
    ###    ##
    ###    ########################################
    ###
    ################################################################################

    ################################################################################
    ###  Enhanced Enchantments:
    ###    Some vanilla enchantments tweaked to scale better.
    ###    Some of these require the enchantment's max level to be increased to take full advantage of the tweak.
    ###
    ###    ########################################
    ###    ##  More Binding:
    ###    ##    Enabling this tweak will allow Curse of Binding to scale with enchantment level.
    ###    ##    Higher levels will decrease the chance of the item dropping on death.
    ###    ##    The effect maxes out at Curse of Binding X, Binding I is kept the same as vanilla.
    ###    ##    Formula: Drop Chance on Death = 1.1 - 0.1 * bindingLevel.
    ###    ##
                 more_binding=true
    ###    ##
    ###    ########################################
    ###    ##  More Channeling:
    ###    ##    Enabling this tweak will allow Channeling to scale with enchantment level.
    ###    ##    Channeling I only works during thunderstorms.
    ###    ##    Channeling II will allow Channeling to work during rain.
    ###    ##    No scaling for higher levels.
    ###    ##
                 more_channeling=true
    ###    ##
    ###    ########################################
    ###    ##  More Flame:
    ###    ##    Enabling this tweak will allow Flame to scale with enchantment level.
    ###    ##    Flame I lasts 5 seconds. Each additional level adds 2 seconds.
    ###    ##    Continues scaling for higher levels (uncapped).
    ###    ##    Formula: Burn Duration = 5 + 2 * flameLevel.
    ###    ##
                 more_flame=true
    ###    ##
    ###    ########################################
    ###    ##  More Infinity:
    ###    ##    Overrides BowInfinityFix.
    ###    ##    Enabling this tweak will allow Infinity to scale with enchantment level.
    ###    ##    Lets bows with Infinity have a chance at shooting without consuming an arrow.
    ###    ##    Continues scaling for higher levels (capped at 100% chance).
    ###    ##    Formula: Free Arrow Chance = 0.03 * infinityLevel. (+3% chance per level)
    ###    ##
                 more_infinity=true
    ###    ##
    ###    ########################################
    ###    ##  More Mending:
    ###    ##    Enabling this tweak will allow Mending to scale with enchantment level.
    ###    ##    Mending II is the same as vanilla Mending.
    ###    ##    Mending I has ~10% XP efficiency loss and Mending III has ~10% XP efficiency gain.
    ###    ##    The effect maxes out at Mending X.
    ###    ##    Formula: Repair Cost = 0.6 - 0.05 * mendingLevel.
    ###    ##
                 more_mending=true
    ###    ##
    ###    ########################################
    ###    ##  More Multishot:
    ###    ##    Enabling this tweak will allow Multishot to scale with enchantment level.
    ###    ##    Each additional level will add 2 arrows to the shot.
    ###    ##    Crossbows take damage for each Multishot arrow shot.
    ###    ##    Continues scaling for higher levels (uncapped).
    ###    ##
                 more_multishot=true
    ###    ##
    ###    ########################################
    ###
    ################################################################################

    ################################################################################
    ###  Other Tweaks:
    ###    Some small tweaks that don't fit into the other categories.
    ###    These are some of the more popular ones.
    ###
    ###    ########################################
    ###    ##  Axes are Not Tools:
    ###    ##    Normally axes are treated as tools when used in combat.
    ###    ##    This causes them to take double durability damage when they are used in combat.
    ###    ##    Enabling this tweak removes the double durability damage penalty.
    ###    ##
                 axes_not_tools=true
    ###    ##
    ###    ########################################
    ###    ##  Axe Weapons:
    ###    ##    Allow the addition of some weapon enchantments that normally can not be added onto axes.
    ###    ##    Enabling this tweak allows you to add the following enchantments to axes: Fire Aspect, Knockback, and Looting.
    ###    ##
                 axe_weapons=true
    ###    ##
    ###    ########################################
    ###    ##  Better Mending:
    ###    ##    Normally Mending will only repair an item if it is being held or worn by the player.
    ###    ##    Enabling this tweak will allow Mending to be more flexible with what it can repair.
    ###    ##    Mending order: Main-Hand -> Off-Hand -> Armor -> Hotbar -> Inventory.
    ###    ##
                 better_mending=true
    ###    ##
    ###    ########################################
    ###    ##  Bow Infinity Fix:
    ###    ##    Normally even though you have Infinity on a bow, you need to have arrows in your inventory to shoot.
    ###    ##    Enabling this tweak will allow you to shoot arrows without having them in your inventory.
    ###    ##
                 bow_infinity_fix=false
    ###    ##
    ###    ########################################
    ###    ##  God Armor:
    ###    ##    Allow the combination of damage negation enchantments that normally can not be added together.
    ###    ##    Enabling this tweak allows you to combine the following enchantments: Protection, Blast Protection, Fire Protection, and Projectile Protection.
    ###    ##
                 god_armor=true
    ###    ##
    ###    ########################################
    ###    ##  God Weapons:
    ###    ##    Allow the combination of damage enhancement enchantments that normally can not be added together.
    ###    ##    Enabling this tweak allows you to combine the following enchantments: Sharpness, Smite, and Bane of Arthropods.
    ###    ##
                 god_weapons=true
    ###    ##
    ###    ########################################
    ###    ##  Infinite Mending:
    ###    ##    Normally you need to choose between having either Mending or Infinity.
    ###    ##    Enabling this tweak allows both enchantments to coexist.
    ###    ##
                 infinite_mending=true
    ###    ##
    ###    ########################################
    ###    ##  Loyal Void Tridents:
    ###    ##    Normally tridents enchanted with Loyalty will be lost if thrown into the void.
    ###    ##    Enabling this tweak will allow those tridents to return to the player.
    ###    ##
                 loyal_void_tridents=true
    ###    ##
    ###    ########################################
    ###    ##  Multishot Piercing:
    ###    ##    Normally you need to choose between having either Multishot or Piercing.
    ###    ##    Enabling this tweak allows both enchantments to coexist.
    ###    ##
                 multishot_piercing=true
    ###    ##
    ###    ########################################
    ###    ##  No Soul Speed Backlash:
    ###    ##    Normally boots will take damage when walking on soul sand with Soul Speed.
    ###    ##    Enabling this tweak will prevent your boots from taking damage from the enchantment.
    ###    ##
                 no_soul_speed_backlash=true
    ###    ##
    ###    ########################################
    ###    ##  No Thorns Backlash:
    ###    ##    Normally armor will take damage when Thorns is triggered.
    ###    ##    Enabling this tweak will prevent your armor from taking damage from the enchantment.
    ###    ##
                 no_thorns_backlash=true
    ###    ##
    ###    ########################################
    ###    ##  Shiny Max Enchantment Names:
    ###    ##    Normally everyone knows what the max level for an enchantment is, but what about now?
    ###    ##    Enabling this tweak will color the name of enchantments at max level to be yellow.
    ###    ##    Client-side installation is required for this tweak.
    ###    ##
                 shiny_name=true
    ###    ##
    ###    ########################################
    ###    ##  Trident Weapons:
    ###    ##    Allow the addition of some weapon enchantments that normally can not be added to tridents.
    ###    ##    Enabling this tweak allows you to add the following enchantments to tridents: Sharpness, Smite, Bane of Arthropods, Fire Aspect, Knockback, and Looting.
    ###    ##
                 trident_weapons=true
    ###    ##
    ###    ########################################
    ###
    ################################################################################

    ################################################################################
    ###  Modify Max Enchantment Levels:
    ###    This is useful if you want to make individual enchantments more powerful or less powerful.
    ###    Not all vanilla enchantments scale by default, some have capped effects at certain levels.
    ###    For example: Protection 255 would still be affected by vanilla's 25 EPF cap despite going far above it.
    ###    To avoid these limits you can enable a tweak from the 'Enhanced Enchantments' section (if available).
    ###
    ###    Accepted values: 1-255, 10 (enabled), 3 (default)
    ###
    ###    ########################################
    ###    ##   Master Switch (Capmod):
    ###    ##    Enable/Disable the ability to modify max enchantment levels.
    ###    ##
                 capmod_enabled=Enabled
    ###    ##
    ###    ########################################
    ###
    ###    ########################################
    ###    ##  Armor Enchantments:
    ###    ##
                 aqua_affinity=-2
                 blast_protection=-10
                 depth_strider=-5
                 feather_falling=-10
                 fire_protection=-10
                 frost_walker=-3
                 projectile_protection=-10
                 protection=-10
                 respiration=-10
                 soul_speed=-5
                 swift_sneak=-5
                 thorns=-5
    ###    ##
    ###    ########################################
    ###    ##  Curse Enchantments:
    ###    ##
                 binding_curse=-3
                 vanishing_curse=-3
    ###    ##
    ###    ########################################
    ###    ##  Melee Enchantments:
    ###    ##
                 bane_of_arthropods=-10
                 fire_aspect=-5
                 impaling=-5
                 knockback=-3
                 looting=-5
                 sharpness=-10
                 smite=-10
                 sweeping_edge=-5
    ###    ##
    ###    ########################################
    ###    ##  Ranged Enchantments:
    ###    ##
                 channeling=-2
                 flame=-3
                 infinity=-1
                 loyalty=-5
                 multishot=-3
                 piercing=-5
                 power=-10
                 punch=-3
                 quick_charge=-5
                 riptide=-5
    ###    ##
    ###    ########################################
    ###    ##  Tool Enchantments:
    ###    ##
                 efficiency=-10
                 fortune=-10
                 lure=-10
                 luck_of_the_sea=-10
                 mending=-3
                 silk_touch=-1
                 unbreaking=-10
    ###    ##
    ###    ########################################
    ###
    ################################################################################

####################################################################################################
####  End of Enchant Tweaker Config
####################################################################################################

**Comment by DeadlyWolf3** [comment]
and this is one i tried before editing the config 
and another thing the infinity works with mending but infinity itself doesn't work anymore with 1 arrow i need every shot 1 arrow like i dont have infinity on my bow
####################################################################################################
####  Enchant Tweaker Config
####################################################################################################

    ################################################################################
    ###   Master Switch:
    ###    Enable/Disable the entire mod.
    ###
           mod_enabled=true
    ###
    ################################################################################

    ################################################################################
    ###  Anvil Tweaks:
    ###    Some small anvil related tweaks. Lightly alters the anvil's mechanics.
    ###
    ###    ########################################
    ###    ##  Cheap Names:
    ###    ##    Normally renaming an item will cost a similar amount of levels as adding an enchantment onto an item.
    ###    ##    Enabling this will force the cost for renaming items to always be one level.
    ###    ##    For those who don't enjoy spending nineteen levels to rename a pickaxe... again.
    ###    ##
                 cheap_names=false
    ###    ##
    ###    ########################################
    ###    ##  Not Too Expensive:
    ###    ##    Normally once an item's enchant/repair cost reaches 40 levels you can no longer enchant or repair it.
    ###    ##    Enabling this tweak alters the "Too Expensive!" mechanic in the anvil changing the level it activates at to one of your choosing.
    ###    ##    Client-side install will hide the "Too Expensive!" message. Otherwise, it will still appear but will not prevent the action.
    ###    ##
                 not_too_expensive=false
                 nte_max_cost=2147483647
    ###    ##
    ###    ########################################
    ###    ##  Prior Work is Cheaper:
    ###    ##    Normally when enchanting/repairing an item, each operation will double the cost of the next action.
    ###    ##    Enabling this tweak will let you customize the penalty.
    ###    ##
                 prior_work_cheaper=false
                 pw_cost_multiplier=1.33
    ###    ##
    ###    ########################################
    ###    ##  Prior Work is Free:
    ###    ##    Normally when enchanting/repairing an item, each operation will double the cost of the next action.
    ###    ##    Enabling this tweak completely disables the prior work penalty for items enchanted/repaired at an anvil.
    ###    ##    This means that the enchant/repair cost for an item will always stay at the minimum value for that given procedure.
    ###    ##
                 prior_work_free=false
    ###    ##
    ###    ########################################
    ###    ##  Sturdy Anvils:
    ###    ##    Normally an anvil has a 12% (0.12) chance to take damage when used.
    ###    ##    Enabling this tweak will let you customize the damage chance.
    ###    ##
                 sturdy_anvils=false
                 anvil_damage_chance=0.06
    ###    ##
    ###    ########################################
    ###
    ################################################################################

    ################################################################################
    ###  Enhanced Enchantments:
    ###    Some vanilla enchantments tweaked to scale better.
    ###    Some of these require the enchantment's max level to be increased to take full advantage of the tweak.
    ###
    ###    ########################################
    ###    ##  More Binding:
    ###    ##    Enabling this tweak will allow Curse of Binding to scale with enchantment level.
    ###    ##    Higher levels will decrease the chance of the item dropping on death.
    ###    ##    The effect maxes out at Curse of Binding X, Binding I is kept the same as vanilla.
    ###    ##    Formula: Drop Chance on Death = 1.1 - 0.1 * bindingLevel.
    ###    ##
                 more_binding=false
    ###    ##
    ###    ########################################
    ###    ##  More Channeling:
    ###    ##    Enabling this tweak will allow Channeling to scale with enchantment level.
    ###    ##    Channeling I only works during thunderstorms.
    ###    ##    Channeling II will allow Channeling to work during rain.
    ###    ##    No scaling for higher levels.
    ###    ##
                 more_channeling=false
    ###    ##
    ###    ########################################
    ###    ##  More Flame:
    ###    ##    Enabling this tweak will allow Flame to scale with enchantment level.
    ###    ##    Flame I lasts 5 seconds. Each additional level adds 2 seconds.
    ###    ##    Continues scaling for higher levels (uncapped).
    ###    ##    Formula: Burn Duration = 5 + 2 * flameLevel.
    ###    ##
                 more_flame=false
    ###    ##
    ###    ########################################
    ###    ##  More Infinity:
    ###    ##    Overrides BowInfinityFix.
    ###    ##    Enabling this tweak will allow Infinity to scale with enchantment level.
    ###    ##    Lets bows with Infinity have a chance at shooting without consuming an arrow.
    ###    ##    Continues scaling for higher levels (capped at 100% chance).
    ###    ##    Formula: Free Arrow Chance = 0.03 * infinityLevel. (+3% chance per level)
    ###    ##
                 more_infinity=false
    ###    ##
    ###    ########################################
    ###    ##  More Mending:
    ###    ##    Enabling this tweak will allow Mending to scale with enchantment level.
    ###    ##    Mending II is the same as vanilla Mending.
    ###    ##    Mending I has ~10% XP efficiency loss and Mending III has ~10% XP efficiency gain.
    ###    ##    The effect maxes out at Mending X.
    ###    ##    Formula: Repair Cost = 0.6 - 0.05 * mendingLevel.
    ###    ##
                 more_mending=false
    ###    ##
    ###    ########################################
    ###    ##  More Multishot:
    ###    ##    Enabling this tweak will allow Multishot to scale with enchantment level.
    ###    ##    Each additional level will add 2 arrows to the shot.
    ###    ##    Crossbows take damage for each Multishot arrow shot.
    ###    ##    Continues scaling for higher levels (uncapped).
    ###    ##
                 more_multishot=false
    ###    ##
    ###    ########################################
    ###
    ################################################################################

    ################################################################################
    ###  Other Tweaks:
    ###    Some small tweaks that don't fit into the other categories.
    ###    These are some of the more popular ones.
    ###
    ###    ########################################
    ###    ##  Axes are Not Tools:
    ###    ##    Normally axes are treated as tools when used in combat.
    ###    ##    This causes them to take double durability damage when they are used in combat.
    ###    ##    Enabling this tweak removes the double durability damage penalty.
    ###    ##
                 axes_not_tools=false
    ###    ##
    ###    ########################################
    ###    ##  Axe Weapons:
    ###    ##    Allow the addition of some weapon enchantments that normally can not be added onto axes.
    ###    ##    Enabling this tweak allows you to add the following enchantments to axes: Fire Aspect, Knockback, and Looting.
    ###    ##
                 axe_weapons=false
    ###    ##
    ###    ########################################
    ###    ##  Better Mending:
    ###    ##    Normally Mending will only repair an item if it is being held or worn by the player.
    ###    ##    Enabling this tweak will allow Mending to be more flexible with what it can repair.
    ###    ##    Mending order: Main-Hand -> Off-Hand -> Armor -> Hotbar -> Inventory.
    ###    ##
                 better_mending=false
    ###    ##
    ###    ########################################
    ###    ##  Bow Infinity Fix:
    ###    ##    Normally even though you have Infinity on a bow, you need to have arrows in your inventory to shoot.
    ###    ##    Enabling this tweak will allow you to shoot arrows without having them in your inventory.
    ###    ##
                 bow_infinity_fix=false
    ###    ##
    ###    ########################################
    ###    ##  God Armor:
    ###    ##    Allow the combination of damage negation enchantments that normally can not be added together.
    ###    ##    Enabling this tweak allows you to combine the following enchantments: Protection, Blast Protection, Fire Protection, and Projectile Protection.
    ###    ##
                 god_armor=false
    ###    ##
    ###    ########################################
    ###    ##  God Weapons:
    ###    ##    Allow the combination of damage enhancement enchantments that normally can not be added together.
    ###    ##    Enabling this tweak allows you to combine the following enchantments: Sharpness, Smite, and Bane of Arthropods.
    ###    ##
                 god_weapons=false
    ###    ##
    ###    ########################################
    ###    ##  Infinite Mending:
    ###    ##    Normally you need to choose between having either Mending or Infinity.
    ###    ##    Enabling this tweak allows both enchantments to coexist.
    ###    ##
                 infinite_mending=false
    ###    ##
    ###    ########################################
    ###    ##  Loyal Void Tridents:
    ###    ##    Normally tridents enchanted with Loyalty will be lost if thrown into the void.
    ###    ##    Enabling this tweak will allow those tridents to return to the player.
    ###    ##
                 loyal_void_tridents=false
    ###    ##
    ###    ########################################
    ###    ##  Multishot Piercing:
    ###    ##    Normally you need to choose between having either Multishot or Piercing.
    ###    ##    Enabling this tweak allows both enchantments to coexist.
    ###    ##
                 multishot_piercing=false
    ###    ##
    ###    ########################################
    ###    ##  No Soul Speed Backlash:
    ###    ##    Normally boots will take damage when walking on soul sand with Soul Speed.
    ###    ##    Enabling this tweak will prevent your boots from taking damage from the enchantment.
    ###    ##
                 no_soul_speed_backlash=false
    ###    ##
    ###    ########################################
    ###    ##  No Thorns Backlash:
    ###    ##    Normally armor will take damage when Thorns is triggered.
    ###    ##    Enabling this tweak will prevent your armor from taking damage from the enchantment.
    ###    ##
                 no_thorns_backlash=false
    ###    ##
    ###    ########################################
    ###    ##  Shiny Max Enchantment Names:
    ###    ##    Normally everyone knows what the max level for an enchantment is, but what about now?
    ###    ##    Enabling this tweak will color the name of enchantments at max level to be yellow.
    ###    ##    Client-side installation is required for this tweak.
    ###    ##
                 shiny_name=false
    ###    ##
    ###    ########################################
    ###    ##  Trident Weapons:
    ###    ##    Allow the addition of some weapon enchantments that normally can not be added to tridents.
    ###    ##    Enabling this tweak allows you to add the following enchantments to tridents: Sharpness, Smite, Bane of Arthropods, Fire Aspect, Knockback, and Looting.
    ###    ##
                 trident_weapons=false
    ###    ##
    ###    ########################################
    ###
    ################################################################################

    ################################################################################
    ###  Modify Max Enchantment Levels:
    ###    This is useful if you want to make individual enchantments more powerful or less powerful.
    ###    Not all vanilla enchantments scale by default, some have capped effects at certain levels.
    ###    For example: Protection 255 would still be affected by vanilla's 25 EPF cap despite going far above it.
    ###    To avoid these limits you can enable a tweak from the 'Enhanced Enchantments' section (if available).
    ###
    ###    Accepted values: 1-255, 0 (disabled), -1 (default)
    ###
    ###    ########################################
    ###    ##   Master Switch (Capmod):
    ###    ##    Enable/Disable the ability to modify max enchantment levels.
    ###    ##
                 capmod_enabled=false
    ###    ##
    ###    ########################################
    ###
    ###    ########################################
    ###    ##  Armor Enchantments:
    ###    ##
                 aqua_affinity=-1
                 blast_protection=-1
                 depth_strider=-1
                 feather_falling=-1
                 fire_protection=-1
                 frost_walker=-1
                 projectile_protection=-1
                 protection=-1
                 respiration=-1
                 soul_speed=-1
                 swift_sneak=-1
                 thorns=-1
    ###    ##
    ###    ########################################
    ###    ##  Curse Enchantments:
    ###    ##
                 binding_curse=-1
                 vanishing_curse=-1
    ###    ##
    ###    ########################################
    ###    ##  Melee Enchantments:
    ###    ##
                 bane_of_arthropods=-1
                 fire_aspect=-1
                 impaling=-1
                 knockback=-1
                 looting=-1
                 sharpness=-1
                 smite=-1
                 sweeping_edge=-1
    ###    ##
    ###    ########################################
    ###    ##  Ranged Enchantments:
    ###    ##
                 channeling=-1
                 flame=-1
                 infinity=-1
                 loyalty=-1
                 multishot=-1
                 piercing=-1
                 power=-1
                 punch=-1
                 quick_charge=-1
                 riptide=-1
    ###    ##
    ###    ########################################
    ###    ##  Tool Enchantments:
    ###    ##
                 efficiency=-1
                 fortune=-1
                 lure=-1
                 luck_of_the_sea=-1
                 mending=-1
                 silk_touch=-1
                 unbreaking=-1
    ###    ##
    ###    ########################################
    ###
    ################################################################################

####################################################################################################
####  End of Enchant Tweaker Config
####################################################################################################

**Comment by adibarra** [comment]
I see what the problem is here. It is these two lines:
```
mod_enabled=Enable
capmod_enabled=Enabled
```

Make sure you change them to:
```
mod_enabled=true
capmod_enabled=true
```

Additionally if you want the bow to have infinity work the way you described then change:
```bow_infinity_fix=false``` to ```bow_infinity_fix=true```.

And, last but not least, In the enchantment level cap section it looks like you filled them all in with negative numbers. Remove the ```-``` from the numbers and they should work fine. Only keep ```-1``` for the ones that you don't want to change from their default vanilla settings.

Let me know if this resolves your issue or if you continue to experience problems.

**Comment by DeadlyWolf3** [comment]
it worked now thnx but the infinity not worked with that enabled with both false it seems to work
bow_infinity_fix=false 
more_infinity=False

and i assume the cost of each above the normal max lvls cost high bc i saw it cost alrdy 40lvls to lvl 4 lure and stuff
