### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by DeadlyWolf3** [adibarra/enchant-tweaker#42]
### What happened?

mod not working in singleplayer

### What should have happened?

that i could've enchant to higher lvls then the standard one

### How to reproduce?

idk what this means ???

### What is the jar file name?

enchanttweaker-1.4.9+mc1.20.3-1.20.4 (1).jar

### What Minecraft version?

fabric 1.20.4

### Anything else?

i cant put the config file in the relevant logs?

### Before submitting...

- [ ] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
#41
