### ISSUE TITLE
feat: Update to 1.21?

### ISSUE THREAD

**Issue by IVIPOWER** [adibarra/enchant-tweaker#43]
### What does it do?

Maybe update it to 1.21, might be a good idea since the trials and the new enchantments that it involves

### Why add it?

why not?

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by IVIPOWER** [comment]
the not too expensive part is so useful btw

**Comment by IVIPOWER** [comment]
is this something is gonna happen or not?

**Comment by adibarra** [comment]
Not as of right now. Check out issue #36 for more info.
