### ISSUE TITLE
bug: ExceptionInInitializerError on server when installed alongside Axes Are Weapons

### ISSUE THREAD

**Issue by GiienaAstrella** [adibarra/enchant-tweaker#5]
### What happened?

When installed on a clean Fabric server with just [Axes Are Weapons](https://modrinth.com/mod/axes-are-weapons) and its dependencies, the server crashes on launch with `java.lang.ExceptionInInitializerError`.

### What should have happened?

At the bare minimum, the server should launch.

### How to reproduce?

1. Install a Fabric server
2. Install Enchant Tweaker, Axes Are Weapons, [Cloth Config](https://modrinth.com/mod/cloth-config), and [Fabric API](https://modrinth.com/mod/fabric-api).
3. Launch the server

### What is the jar file name?

enchanttweaker-1.4.0+mc1.19.4.jar

### Any relevant logs?

[latest.log](https://mclo.gs/dzqarDC)

### Anything else?

Given it looks like it's a mixin issue, this could be related to #4. That said, it's hard to tell given the lack of verbosity in the logs generated by the game for that issue. And just for your convenience, I have listed version numbers of the environment below.

**Mod Version:** 1.4.0+mc1.19.4
**Fabric Loader Version:** 0.14.19
**Fabric API Version:** 0.81.1
**Minecraft Version:** 1.19.4
**Java Version:**
```
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
Looks like both mods modify the same piece of code which causes the issue. Easy fix, simply going to disable injection for our version of the tweak if 'Axes Are Weapons' is installed. That should let you install both mods at once. It'll be included in the next update (v1.4.1). Thanks for the bug report!
