### ISSUE TITLE
feat: 1.20/1.20.1 Support

### ISSUE THREAD

**Issue by CaseyPurser** [adibarra/enchant-tweaker#6]
### What does it do?

Supports the newest version of Minecraft.

### Why add it?

To support servers that rely on this mod.

### Before submitting...

- [X] This issue is not a duplicate of an existing issue (open or closed).

**Comment by adibarra** [comment]
I'll look into what it would take to support the newer versions.

**Comment by adibarra** [comment]
Just finished it, they'll be supported in the next update (v1.4.3).
